2025-05-23 20:32:35,040 - INFO - [logging.py:51] - ==================================================
2025-05-23 20:32:35,040 - INFO - [logging.py:52] - Application starting at 2025-05-23 20:32:35
2025-05-23 20:32:35,040 - INFO - [logging.py:53] - Logging initialized at level INFO
2025-05-23 20:32:35,040 - INFO - [logging.py:54] - Log file: logs\nc_client_20250523_203235.log
2025-05-23 20:32:35,040 - INFO - [logging.py:55] - ==================================================
2025-05-23 20:32:35,040 - INFO - [main.py:27] - NetControl Client starting...
2025-05-23 20:32:44,163 - INFO - [encryption.py:27] - AES encryption initialized successfully
2025-05-23 20:32:44,164 - INFO - [client.py:93] - Connected to central server at 192.168.1.120:5001 with AES encryption
2025-05-23 20:32:44,187 - INFO - [client.py:150] - Successfully logged in as admin
2025-05-23 20:32:44,430 - INFO - [system_monitor.py:31] - Starting resource monitoring
2025-05-23 20:32:44,430 - INFO - [system_monitor.py:27] - Hardware monitoring thread started
2025-05-23 20:32:44,430 - INFO - [manager.py:559] - Starting connection health monitoring
2025-05-23 20:32:44,430 - INFO - [manager.py:555] - Connection health monitoring thread started
2025-05-23 20:32:48,008 - INFO - [manager.py:81] - Connection established with 192.168.1.120:5000 using AES encryption
2025-05-23 20:32:48,067 - INFO - [encryption.py:27] - AES encryption initialized successfully
2025-05-23 20:32:48,599 - INFO - [client.py:331] - Registered server 192.168.1.120:5000
2025-05-23 20:32:48,605 - ERROR - [client.py:464] - Setting sharing status failed: no such table: active_connections
2025-05-23 20:32:48,605 - WARNING - [client.py:339] - Failed to share server 192.168.1.120:5000: no such table: active_connections
2025-05-23 20:32:48,612 - INFO - [manager.py:179] - Successfully registered server 192.168.1.120:5000 with central server
2025-05-23 20:32:48,617 - ERROR - [client.py:464] - Setting sharing status failed: no such table: active_connections
2025-05-23 20:32:48,617 - WARNING - [manager.py:193] - Failed to enable sharing for 192.168.1.120:5000: no such table: active_connections
2025-05-23 20:32:55,970 - INFO - [manager.py:652] - All connections closed
2025-05-23 20:32:55,971 - INFO - [main_window.py:248] - Application shutting down
2025-05-23 20:32:55,971 - INFO - [main.py:39] - NetControl Client shutdown
